### ISSUE TITLE
Crash on template function with class template argument

### ISSUE THREAD

**Issue by senier** [Componolit/Cappulada#50]
When we instantiate  a template function with a class as the template argument, Clang crashes. This does not happen with primitive types.

```C++
namespace Foo {                                                                                                                                

   class Bar { };

   template<typename T>
   struct Baz {
      void fun(Baz);
   };

   template<> void Baz<Bar>::fun(Baz<Bar>) {};
}
```

Crash:

```
======================================================================
FAIL: test_template_with_class_argument (__main__.Regression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testregression.py", line 9, in test_template_with_class_argument
    unused = CXX("tests/data/test_template_class_argument.h").ToIR(project="Capdpa")
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 309, in ToIR
    children = self.__convert_children(self.translation_unit.cursor.get_children())
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 260, in __convert_children
    children.append(self.__convert_namespace(cursor))
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 229, in __convert_namespace
    children = self.__convert_children(cursor.get_children())
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 277, in __convert_children
    children.append(self.__convert_function(cursor))
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 73, in __convert_function
    parameters = self.__convert_arguments(cursor.get_children()),
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 198, in __convert_arguments
    ptype = self.__convert_type(list(cursor.get_children()), cursor.type)
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 111, in __convert_type
    args.append(self.__convert_type(children, type_cursor.get_template_argument_type(i)))
  File "/home/alex/Devel/src/capdpa/capdpa/cxx.py", line 104, in __convert_type
    decl = type_cursor.get_declaration()
  File "/usr/lib/python2.7/dist-packages/clang/cindex.py", line 1879, in get_declaration
    return conf.lib.clang_getTypeDeclaration(self)
  File "/usr/lib/python2.7/dist-packages/clang/cindex.py", line 1552, in from_result
    assert tu is not None
AssertionError
```

**Comment by jklmnn** [comment]
This seems to have something to do with the full template specialization you did at
```C++
template<> void Baz<Bar>::fun(Baz<Bar>) {};
```
Another test with a full specialization lead to a similar crash. Maybe it is connected to the fact that full specializations are treated as classes instead of templates?
I tried upgrading to clang 6.0 but this doesn't fix the error.

**Comment by jklmnn** [comment]
Switching to a newer version of clang also brings many new features that break some tests.
