### ISSUE TITLE
Test Cappulada on Genode block interface

### ISSUE THREAD

**Issue by senier** [Componolit/Cappulada#72]

**Comment by jklmnn** [comment]
I first create some minimal examples for the Block interfaces in C++. The work is done in https://github.com/jklmnn/genode/tree/cappulada.

**Comment by jklmnn** [comment]
When cloning Genode into the root of this repository the correct command is:
```
./cappulada -o out -p Genode genode/repos/os/include/block_session/connection.h -- -Wno-everything -I genode/repos/os/include -I genode/repos/base/include/ -I genode/repos/base/include/spec/64bit -I genode/repos/base/include/spec/x86 -I genode/repos/base/include/spec/x86_64 -I /usr/local/genode-gcc/bin/../lib/gcc/x86_64-pc-elf/6.3.0/include
```

**Comment by jklmnn** [comment]
With 13c928e325179f0034449297a4c5bf3a5ee2ba5a the block interface runs through completely although I have not tested the output yet.

**Comment by senier** [comment]
Gorgeous!

With current Genode staging and Cappulada 13c928e325179f0034449297a4c5bf3a5ee2ba5a I get an error when using the above command line:

```$ ./cappulada -o out -p Genode genode/repos/os/include/block_session/connection.h -- -Wno-everything -I genode/repos/os/include -I genode/repos/base/include/ -I genode/repos/base/include/spec/64bit -I genode/repos/base/include/spec/x86 -I genode/repos/base/include/spec/x86_64 -I /usr/local/genode-gcc/bin/../lib/gcc/x86_64-pc-elf/6.3.0/include
Traceback (most recent call last):
  File "./cappulada", line 25, in <module>
    generator.run()
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/generator.py", line 147, in run
    spec_private=self.spec_private)
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 464, in ToIR
    children = self.__convert_children(self.translation_unit.cursor.get_children()),
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 378, in __convert_children
    children.append(self.__convert_namespace(cursor))
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 330, in __convert_namespace
    children = self.__convert_children(cursor.get_children())
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 378, in __convert_children
    children.append(self.__convert_namespace(cursor))
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 330, in __convert_namespace
    children = self.__convert_children(cursor.get_children())
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 380, in __convert_children
    decl = self.__convert_class(cursor)
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 92, in __convert_class
    children = self.__convert_children(cursor.get_children()),
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/Cappulada/capdpa/cxx.py", line 430, in __convert_children
    raise NotImplementedError("Unsupported public cursor kind: {} at {}".format(cursor.kind, cursor.location))
NotImplementedError: Unsupported public cursor kind: CursorKind.TEMPLATE_REF at <SourceLocation file 'genode/repos/base/include/base/rpc.h', line 128, column 37>

```

Am I missing anything?

**Comment by jklmnn** [comment]
I'm still on 18.11 so I have to check with debt staging again.

**Comment by jklmnn** [comment]
I was still testing against `meta.h`. When trying `connection.h` the same error appears with current master.

**Comment by jklmnn** [comment]
The error is caused by
```C++
template <> struct Exc_list<Meta::Type_list<> > { typedef Meta::Empty Type; };
```
I have to admit that I don't really understand this statement and what it means. Assuming that it is only a type container and doesn't contain any memory relevant members I'd suggest to ignore it.

**Comment by jklmnn** [comment]
A stacktrace with an `INVALID` error gets generated when a function in a class has a parameter that is a template which resides in another namespace and gets instantiated with a class.
```
======================================================================
ERROR: test_function_template_argument (__main__.Parser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testconvert.py", line 780, in test_function_template_argument
    result = CXX("tests/data/convert/test_function_template_argument.h").ToIR(project="Capdpa")
  File "./capdpa/cxx.py", line 477, in ToIR
    children = self.__convert_children(self.translation_unit.cursor.get_children()),
  File "./capdpa/cxx.py", line 387, in __convert_children
    children.append(self.__convert_namespace(cursor))
  File "./capdpa/cxx.py", line 338, in __convert_namespace
    children = self.__convert_children(cursor.get_children())
  File "./capdpa/cxx.py", line 389, in __convert_children
    decl = self.__convert_class(cursor)
  File "./capdpa/cxx.py", line 92, in __convert_class
    children = self.__convert_children(cursor.get_children()),
  File "./capdpa/cxx.py", line 407, in __convert_children
    children.append(self.__convert_method(cursor))
  File "./capdpa/cxx.py", line 115, in __convert_method
    parameters = self.__convert_arguments(cursor.get_children()),
  File "./capdpa/cxx.py", line 290, in __convert_arguments
    ptype = self.__convert_type(list(cursor.get_children()), cursor.type)
  File "./capdpa/cxx.py", line 177, in __convert_type
    args.append(self.__convert_type(children, child_arg.type.get_declaration().type))
  File "./capdpa/cxx.py", line 283, in __convert_type
    raise NotImplementedError("Unsupported type: {} (from {})".format(type_cursor.kind, type_cursor.spelling))
NotImplementedError: Unsupported type: TypeKind.INVALID (from )
```

**Comment by senier** [comment]
We need to wait for #90 to solve this issue.
